#!/bin/bash
#
# =================================================================================================
# BayLum.CHECK_AND_BUILD shell script
# author: Sebastian Kreutzer
# date: 2017-06-14
#
# Customized R check and build routine for the R package 'BayLum'
# =================================================================================================
#
#
# CONFIG AND DEFINITIONS
# =================================================================================================
#
export TERM=xterm
PATHPACKAGE=$(dirname $0)

#
check_status(){
  if [ $? == 0 ]; then
    echo "[OK]"
  else
    echo "[FAILED]"
  fi
}
#
#
# REMOVING UNWANTED FILES
# =================================================================================================
echo ""
echo -ne "Set package path to " ${PATHPACKAGE} "\n\n"
echo "[PREPARE FOR PACKAGE CHECK]"
echo ""
#

  echo -ne "-> Clean BayLum.BuildResults folder ... \t"
  find ${PATHPACKAGE}/BayLum.BuildResults -type f -exec rm {} \;
  check_status

  echo -ne "-> Remove .DS_Store ... \t\t\t"
  find ${PATHPACKAGE} -name ".DS_Store" -depth -exec rm {} \;
  check_status

  echo -ne "-> Remove .Rhistory ... \t\t\t"
  find ${PATHPACKAGE} -name ".Rhistory" -depth -exec rm {} \;
  check_status

  echo -ne "-> Remove .RData ... \t\t\t\t"
  find ${PATHPACKAGE} -name ".RData" -depth -exec rm {} \;
  check_status


# REMOVE NAMESPACE
# =================================================================================================
  echo -ne "-> Remove NAMESPACE ... \t\t\t"
  find ${PATHPACKAGE} -name "NAMESPACE" -depth -exec rm {} \;
  check_status


# roxygen2
# =================================================================================================
  echo -ne "-> Create empty NAMESPACE file... \t\t"
  echo '# Generated by roxygen2 (4.1.0.9001): do not edit by hand' > NAMESPACE
  check_status

  echo -ne "-> Build documentation ... \t\t\t"
  eval R CMD BATCH --no-timing ${PATHPACKAGE}/BayLum.BuildScripts/BayLum.PBS_roxygen2.R /dev/null
  check_status


#
# BUILD PACKAGE
# =================================================================================================
echo ""
echo "[BUILD PACKAGE]"
echo ""

  eval R CMD build ${PATHPACKAGE}


#
# CHECK PACKAGE
# =================================================================================================
echo ""
echo "[CHECK PACKAGE]"
echo ""

  ##eval R CMD check --timings --as-cran ${PATHPACKAGE}/BayLum*.tar.gz
  eval R CMD check --timings ${PATHPACKAGE}/BayLum*.tar.gz

#
# INSTALL PACKAGE
# =================================================================================================
echo ""
echo "[INSTALL PACKAGE]"
echo ""

  eval R CMD INSTALL --build ${PATHPACKAGE}/BayLum*.tar.gz

#
# COPY FILES AND CLEANING UP
# =================================================================================================
echo ""
echo "[OUTRO]"
echo ""

  echo -ne "-> Write BibTeX ... \t\t\t\t"
  eval R CMD BATCH --no-timing ${PATHPACKAGE}/BayLum.BuildScripts/BayLum.PBS_BibTeX.R /dev/null
  check_status

#
# COMPILE FUNCTION PARAMETER LIST
# =================================================================================================


  echo -ne "-> Moving packge source files (*.tar.gz) ... \t"
  mv BayLum_*.tar.gz BayLum.BuildResults/ &>/dev/null
  check_status

  echo -ne "-> Moving packge compiles package (*.tgz) ... \t"
  mv BayLum_*.tgz BayLum.BuildResults/ &>/dev/null
  check_status

  echo -ne "-> Copy manual ... \t\t\t\t"
  cp BayLum.Rcheck/BayLum-manual.pdf BayLum.BuildResults/BayLum-manual.pdf &>/dev/null
  check_status

  echo -ne "-> Copy check results ... \t\t\t"
  cp BayLum.Rcheck/BayLum-Ex.pdf BayLum.BuildResults/BayLum-Ex.pdf &>/dev/null
  check_status

  echo -ne "-> Remove BayLum.Rcheck ... \t\t\t"
  rm -r ${PATHPACKAGE}/BayLum.Rcheck &>/dev/null
  check_status

  echo ""
  echo "[FINE]"
