#' Plots L/T as a function of regenerative dose
#' 
#' This function plots L/T values as a function of Regenerative Dose, for every selected aliquot.
#' 
#' @param DATA list of objects: LT, sLT, ITimes, dLab, ddot_env, regDose, J, K, Nb_measurement, provided by the function \code{\link{Generate_DataFile}}.
#' \code{DATA} can contain information from more than one sample.
#' @param Path character: path to the project folder (the same as the one used in \code{\link{Generate_DataFile}} to provide \code{DATA})
#' @param Names character vector:  list of names of the sub-folders containing the BIN files, 
#' which were used by \code{\link{Generate_DataFile}} to generate the \code{DATA} object.
#' @param BinPerSample integer vector (with default): vector with the number of BIN files per sample,
#' which was used in \code{\link{Generate_DataFile}} to generate the \code{DATA} object.
#' @param SampleNumber integer(with default): ID number (in [1,\code{Nb_sample}]) of the sample selected for plotting L/T as a function of regenerative doses. 
#' Required if the \code{DATA} object contains information for more than one sample.
#' @param sepDP character(with default): column separator in the DiscPose.csv file.
#' 
#' @details To fill \code{Names} and \code{BinPerSample}, we refer to the detail section from the \code{\link{Generate_DataFile}} function. 
#' 
#' @return L/T plots; there are as many plots as selected aliquots in the DiscPos.csv file. There are 9 plots per page. 
#' There is not interpolation.  
#' 
#' @author Claire Christophe, Guillaume Guerin
#' 
#' @seealso \code{\link{Generate_DataFile}}
#' 
#' @examples
#' ## load data file generated by the function Generate_DataFile
#' # data(DATA1,envir = environment()) 
#' # LT_RegenDose(DATA1,Path=c('inst/extdata/'),Names=c("GDB3"))
#' 
#' @export

LT_RegenDose<-function(DATA,Path,Names,BinPerSample=rep(1),SampleNumber=1,sepDP=c(",")){
  
  I=SampleNumber
  par(mfrow=c(3,3))
  CSBinPerSample=cumsum(BinPerSample)
  if(BinPerSample[I]==1){
    index=0
  }else{
    index=rep(0,BinPerSample[I])
    index[2:BinPerSample[I]]=cumsum(DATA$J[(CSBinPerSample[I]-BinPerSample[I]+1):(CSBinPerSample[I]-1)])
  }
  for(bf in 1:BinPerSample[I]){
    for(j in 1:DATA$J[bf+CSBinPerSample[I]-BinPerSample[I]]){
      DP=read.csv(file=paste(Path,Names[(CSBinPerSample[I]-BinPerSample[I]+bf)],"/DiscPos.csv",sep=""),sep=sepDP)
      plot(DATA$regDose[[I]][(index[bf]+j),(1:(DATA$K[(CSBinPerSample[I]-BinPerSample[I]+bf)]))],DATA$LT[[I]][(index[bf]+j),2:(DATA$K[(CSBinPerSample[I]-BinPerSample[I]+bf)]+1)],
           main=c(paste("disc=",DP[j,1],', Pos=',DP[j,2])),xlab="Regen Dose (Gy)", ylab="L/T")
    }
  }
}
