#' Bayesian analysis for the palaeodose estimation of various samples
#'
#' This function computes the palaeodose of one or various samples according to the model developed in Combes et al (2015), 
#' based on an output of the \code{\link{Generate_DataFile}} function.\cr 
#' Samples, for which data is avalilable in several BIN files, can be analysed.
#'
#' @param DATA list of objects: LT, sLT, ITimes, dLab, ddot_env, regDose, J, K, Nb_measurement, 
#' provided by the function \code{\link{Generate_DataFile}}. 
#' \code{DATA} contains information for more than one sample.
#' @param Nb_sample integer \bold{(required)}: number of samples, \code{Nb_sampe>1}.
#' @param BinPerSample integer vector (with default): vector with the number of BIN files per sample. 
#' The length of this vector is equal to \code{Nb_sample}. 
#' \code{BinPerSample}[i] correponds to the number of BIN files for the sample whose number ID is equal to \code{i}.
#' For more information to fill this vector, we refer to detatils in \code{\link{Generate_DataFile}}.
#' @param SampleNames character vector: names of sample. The length of this vector is equal to \code{Nb_sample}.
#' @param SavePdf boolean (with default): if TRUE save graph in pdf file named \code{OutputFileName} in folder \code{OutputFilePath}.
#' @param OutputFileName character (with default): name of the pdf files that will be generated by the function.
#' @param OutputFilePath character (with default): path to the pdf files that will be generated by the function.
#' @param SaveEstimates boolean (with default): if TRUE save Bayes estimates and confidence interval at level 68% and 95%,
#' in a csv table named \code{OutputFileName} in folder \code{OutputFilePath}.
#' @param OutputTableName character (with default): name of the table that will be generated by the function if \code{SaveEstimates}=TRUE.
#' @param OutputTablePath character (with default): path to the table that will be generated by the function if \code{SaveEstimates}=TRUE.
#' @param LIN_fit logical (with default): if TRUE (default) allows a linear component, 
#' on top of the (default) saturating exponential curve, for the fitting of dose response curves.
#' Please see details for more informations on the proposed dose response curves. 
#' @param Origin_fit logical (with default): if TRUE, forces the dose response curves to pass through the origin.
#' Please see details for more informations on the proposed growth curves.
#' @param distribution character (with default): type of distribution that defines
#' how individual equivalent dose values are distributed around the palaeodose. 
#' Allowed inputs are \bold{"cauchy"}, \bold{"gaussian"} and \bold{"lognormal"}.
#' @param Taille integer (with default): number of iterations for the MCMC computation (for more information see \code{\link{jags.model}}).
#' @param t integer (with default): 1 every \code{t} iterations of the MCMC is considered for sampling the posterior distribution
#' (for more information see \code{\link{jags.model}}).
#' @param Nb_chaines integer (with default): number of independent chains for the model (for more information see \code{\link{jags.model}}).
#' 
#' @details 
#' As for \code{\link{Age_Computation}} and \code{\link{AgeS_Computation}}, the user can choose from 4 dose response curves:
#' \itemize{
#'   \item \bold{Saturating exponential plus linear growth} (\code{AgeMultiBF_EXPLIN}):
#'   
#'   for all \code{x} in IR+, \code{f(x)=a(1-exp(-x/b))+cx+d}; select
#'   \itemize{
#'     \item \code{LIN_fit=TRUE}
#'     \item \code{Origin_fit=FALSE}
#'   }
#'   \item \bold{Saturating exponential growth} (\code{AgeMultiBF_EXP}):
#'   
#'   for all \code{x} in IR+, \code{f(x)=a(1-exp(-x/b))+d}; select
#'   \itemize{
#'     \item \code{LIN_fit=FALSE}
#'     \item \code{Origin_fit=FALSE}
#'   }
#'   \item \bold{Saturating exponential plus linear growth and fitting through the origin} (\code{AgeMultiBF_EXPLINZO}):
#'   
#'   for all \code{x} in IR+, \code{f(x)=a(1-exp(-x/b))+cx}; select
#'   \itemize{
#'     \item \code{LIN_fit=TRUE}
#'     \item \code{Origin_fit=TRUE}
#'   }
#'   \item \bold{Saturating exponential growth and fitting through the origin} (\code{AgeMultiBF_EXPZO}):
#'   
#'   for all \code{x} in IR+, \code{f(x)=a(1-exp(-x/b))}; select
#'   \itemize{
#'     \item \code{LIN_fit=FALSE}
#'     \item \code{Origin_fit=TRUE}
#'   }
#' } 
#' 
#' @return  
#' \bold{1- NUMERICAL OUTPUT}\cr
# ______________________
#' 
#' \bold{A list containing the following objects:}
#' \itemize{
#'  \item \bold{Sampling} that corresponds to a sample of the posterior distributions 
#'  of palaeodose and equivalent dose dispersion parameters.
#'  \item \bold{Model_GrowthCurve}, stating which dose response fitting option was chosen;
#'  \item \bold{Distribution}, stating which distribution was chosen to model the dispersion of 
#'  individual equivalent dose values around the palaeodose of the sample; 
#'  \item \bold{PriorAge}, stating the priors used for the age parameter. 
#' }
#' 
#' \bold{The Gelman and Rudin test of convergency}
#' 
#' Prints the result of the Gelman and Rudin test of convergency for palaeodose and equivalent dose dispersion parameters for each sample. 
#' A result close to one is expected.\cr
#' In addition, the user must visually assess the convergency of the trajectories by looking at the pdf file  
#' generated by the function (see 2- for more informations).\cr
#' If both convergencies (Gelman and Rudin test and plot checking) are satisfactory, 
#' the user can consider the printed estimates as valid. Otherwise, the user may try increasing the number of MCMC interations 
#' (\code{Taille}) to reach convergency.
#' 
#' \bold{Credible intervals and Bayes estimates}
#' 
#' Prints the Bayes esitmates, the credible intervals at level 95\% and 68\% for 
#' the palaeodose and equivalent dose dispersion parameters for each sample.
#' 
#' \bold{2- PLOT OUTPUT}
#' 
#' \bold{MCMC trajectories}
#' 
#' A pdf file with the MCMC trajectories and posterior distributions of the palaeodose and equivalent dose dispersion parameters.
#' There is one page per sample. \cr
#' The first line of the figure correponds to the palaeodose parameter and the second to the equivalent dose dispersion parameter. 
#' On each line, the plot on the left represents the MCMC trajectories, and the one on the right the posterior distribution of the parameter. 
#' 
#' @author Claire Christophe, Guillaume Guerin
#' 
#' @seealso 
#' \code{\link{Generate_DataFile}}, \code{\link{rjags}} package, \code{\link{MCMC_plot}}, 
#' \code{\link{Age_Computation}}, \code{\link{SCMatrix}} 
#' 
#' @examples
#' ## Load data
#' # data(DATA1,envir = environment())
#' ## Palaeodose computation of samples GDB3
#' # P=PalaeodoseComputation(DATA1,Nb_sample=1,SampleNames=c("GDB5"),Taille=1000)
#' 
#' @references 
#' Combes, B., Philippe, A., Lanos, P., Mercier, N., Tribolo, C., Guerin, G., Guibert, P., Lahaye, C., 2015. 
#' A Bayesian central equivalent dose model for optically stimulated luminescence dating. 
#' Quaternary Geochronology 28, 62-70. doi:10.1016/j.quageo.2015.04.001
#'
#' @export
#' 

PalaeodoseComputation<-function(DATA,Nb_sample,
                                     BinPerSample=rep(1,Nb_sample),
                                     SampleNames,
                                     SavePdf=FALSE,
                                     OutputFileName=c('MCMCplot',"summary"),
                                     OutputFilePath=c(''),
                                     SaveEstimates=FALSE,
                                     OutputTableName=c("DATA"),
                                     OutputTablePath=c(''),
                                     LIN_fit = TRUE,
                                     Origin_fit = FALSE,
                                     distribution=c("cauchy"),
                                     Taille=50000,t=5,Nb_chaines=3){
  #library(rjags)
  #library(coda)
  #library(lattice)
  #library(ArchaeoPhases)
  
  PriorPalaeodose=c(0,400)
  
  #--Index preparation
  CSBinPerSample=cumsum(BinPerSample)
  LengthSample=c()
  for(ns in 1:Nb_sample){
    LengthSample=c(LengthSample,length(DATA$LT[[ns]][,1]))
  }
  CSLengthSample=c()
  CSLengthSample=c(0,cumsum(LengthSample))
  index2=c(0,cumsum(DATA$J))
  
  #--- File preparation
  LT=matrix(data=0,nrow=sum(DATA$J),ncol=(max(DATA$K)+1))
  sLT=matrix(data=0,nrow=sum(DATA$J),ncol=(max(DATA$K)+1))
  IrrT=matrix(data=0,nrow=sum(DATA$J),ncol=(max(DATA$K)))
  for(ns in 1:Nb_sample){
    LT[seq(CSLengthSample[ns]+1,CSLengthSample[ns+1],1),1:length(DATA$LT[[ns]][1,])]<-DATA$LT[[ns]]
    sLT[seq(CSLengthSample[ns]+1,CSLengthSample[ns+1],1),1:length(DATA$sLT[[ns]][1,])]<-DATA$sLT[[ns]]
    IrrT[seq(CSLengthSample[ns]+1,CSLengthSample[ns+1],1),1:length(DATA$ITimes[[ns]][1,])]<-DATA$ITimes[[ns]]
  }
  
  #--- BUG file selection
  load(paste("inst/BUGFiles/","PalaeodosesMultiBF_EXPLIN",sep=""))
  load(paste("inst/BUGFiles/","PalaeodosesMultiBF_EXPLINZO",sep=""))
  load(paste("inst/BUGFiles/","PalaeodosesMultiBF_EXPZO",sep=""))
  load(paste("inst/BUGFiles/","PalaeodosesMultiBF_EXP",sep=""))
  U=list("PalaeodosesMultiBF_EXPLIN"=PalaeodosesMultiBF_EXPLIN,"PalaeodosesMultiBF_EXPLINZO"=PalaeodosesMultiBF_EXPLINZO,"PalaeodosesMultiBF_EXPZO"=PalaeodosesMultiBF_EXPZO,"PalaeodosesMultiBF_EXP"=PalaeodosesMultiBF_EXP)
  if(LIN_fit==TRUE){
    cLIN=c('LIN')
  }else{cLIN=c()}
  if(Origin_fit==TRUE){
    cO=c("ZO")
  }else{cO=c()}
  Model_GrowthCurve=c(paste("PalaeodosesMultiBF_EXP",cLIN,cO,sep=""))
  
  #--- JAGS run
  dataList = list('N'= LT,'sN'=sLT,"IT"=IrrT,
                  "sDlab"=DATA$dLab[1,],
                  'J'=DATA$J,
                  'K'=DATA$K,
                  "I"=Nb_sample,
                  "index"=index2,
                  "xbound"=PriorPalaeodose,
                  "BinPerSample"=BinPerSample,
                  "CSBinPerSample"=CSBinPerSample)
  jags <- jags.model(textConnection(U[[Model_GrowthCurve]][[distribution]]), data = dataList, n.chains = Nb_chaines, n.adapt=Taille)
  update(jags,Taille)
  echantillon = coda.samples(jags,c("D","sD"),min(Taille,5000),thin=t)
  
  sample=echantillon[[1]]
  for(i in 2:Nb_chaines){
    sample=rbind(sample,echantillon[[i]])
  }
  
  if(SavePdf==TRUE){
    pdf(file=paste(OutputFilePath,OutputFileName[1],".pdf",sep=""),width=8,height=10)
  }
  MCMC_plot(sample,
            size=length(echantillon[[1]][,1]),
            SampleNames=SampleNames,
            Nb_sample=Nb_sample,
            Nb_chaines=Nb_chaines,
            value=c(0,Nb_sample),
            nom=c("D","sD"))
  if(SavePdf==TRUE){
    dev.off()  
  }
  
  ##--- Graphical interpretation, and print result
  
  ##- Gelman and rudin test of convergency of the MCMC
  CV=gelman.diag(echantillon,multivariate=FALSE)
  cat(paste("\n\n>> Convergencies of MCMC of Age parameter <<\n"))
  for(i in 1:Nb_sample){
    cat("----------------------------------------------\n")
    cat(paste(" Sample name: ", SampleNames[i],"\n"))
    cat("---------------------\n")
    cat(paste("\t\t", "Bayes estimate ", "Uppers confidence interval\n"))
    cat(paste(paste("D_",SampleNames[i],sep=""),"\t",round(CV$psrf[i,1],2),"\t\t",round(CV$psrf[i,2],2),"\n"))
    cat(paste(paste("sD_",SampleNames[i],sep=""),"\t",round(CV$psrf[(Nb_sample+i),1],2),"\t\t",round(CV$psrf[(Nb_sample+i),2],2),"\n"))
  }
  
  cat("\n\n________________________________________________________________________________\n")
  cat(" *** WARNING: following informations are only valid if MCMC chains converged  ***\n")
  cat("________________________________________________________________________________\n")  
  
  # Matrix of results
  rnames=c()
  for(i in 1:Nb_sample){
    rnames=c(rnames,paste("D_",SampleNames[i],sep=""),paste("sD_",SampleNames[i],sep=""))
  }
  R=matrix(data=NA,ncol=5,nrow=2*Nb_sample,dimnames=list(rnames,c("lower bound at 95%","lower bound at 68%","Bayes estimate","upper bound at 68%","upper bound at 95%")))
  
  
  ##- Bayes estimate and confidential interval
  cat(paste("\n\n>> Bayes estimates of Age, Palaeodose and its dispersion for each sample and confidence interval <<\n"))
  PalaeodosePlot95=matrix(data=NA,nrow=Nb_sample,ncol=3)
  PalaeodosePlot68=matrix(data=NA,nrow=Nb_sample,ncol=3)
  PalaeodosePlotMoy=rep(0,Nb_sample)
  for(i in 1:Nb_sample){
    cat("----------------------------------------------\n")
    cat(paste(" Sample name: ", SampleNames[i],"\n"))
    cat("---------------------\n")
    
    cat(paste("Parameter", "\t","Bayes estimate","\t"," Confidence interval \n"))
    cat(paste(paste("D_",SampleNames[i],sep=""),"\t",round(mean(sample[,i]),3),'\n'))
    cat("\t\t\t\t\t\t lower bound \t upper bound\n")
    HPD_95=CredibleInterval(sample[,i],0.95)
    HPD_68=CredibleInterval(sample[,i],0.68)
    cat("\t\t\t\t at level 95% \t",round(c(HPD_95[2]),2),"\t\t",round(c(HPD_95[3]),2),"\n")
    cat("\t\t\t\t at level 68% \t",round(c(HPD_68[2]),2),"\t\t",round(c(HPD_68[3]),2),"\n")
    PalaeodosePlot95[i,]=HPD_95
    PalaeodosePlot68[i,]=HPD_68
    PalaeodosePlotMoy[i]=round(mean(sample[,i]),3)
    
    R[(2*(i-1)+1),3]=round(mean(sample[,i]),3)
    R[(2*(i-1)+1),c(1,5)]=round(HPD_95[2:3],3)
    R[(2*(i-1)+1),c(2,4)]=round(HPD_68[2:3],3)
    
    cat(paste("\nParameter", "\t","Bayes estimate","\t"," Confidence interval \n"))
    cat(paste(paste("sD_",SampleNames[i],sep=""),"\t",round(mean(sample[,(Nb_sample+i)]),3),'\n'))
    cat("\t\t\t\t\t\t lower bound \t upper bound\n")
    HPD_95=CredibleInterval(sample[,(Nb_sample+i)],0.95)
    HPD_68=CredibleInterval(sample[,(Nb_sample+i)],0.68)
    cat("\t\t\t\t at level 95% \t",round(c(HPD_95[2]),2),"\t\t",round(c(HPD_95[3]),2),"\n")
    cat("\t\t\t\t at level 68% \t",round(c(HPD_68[2]),2),"\t\t",round(c(HPD_68[3]),2),"\n")
    
    R[(2*(i-1)+2),3]=round(mean(sample[,(Nb_sample+i)]),3)
    R[(2*(i-1)+2),c(1,5)]=round(HPD_95[2:3],3)
    R[(2*(i-1)+2),c(2,4)]=round(HPD_68[2:3],3)
    
  }
  cat("\n----------------------------------------------\n")
  
  if(SaveEstimates==TRUE){
    write.csv(R,file=c(paste(OutputTablePath,"Estimates",OutputTableName,".csv",sep="")))
  }
  
  Info=list("Sampling"=echantillon,"Model_GrowthCurve"=Model_GrowthCurve, "Distribution"=distribution)
  return(Info)
  
}
