# CI GitHub Action ... adapted from usethis::use_github_actions()
on:
  push:
    branches: [master]

  pull_request:
    branches: [master, new_feature]

name: GitHub Actions CI

## change if caches needs to be refreshed
env:
  cache-version: v4

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy:
      fail-fast: false
      matrix:
        config:
        - {os: windows-latest, r: 'release', not_cran: 'true'}
        - {os: macos-12, r: 'release', not_cran: 'true'}
        - {os: ubuntu-latest,   r: 'devel', not_cran: 'true'}
        - {os: ubuntu-latest,   r: 'release', not_cran: 'true'}
        - {os: ubuntu-latest,   r: 'oldrel', not_cran: 'true'}

    env:
      _R_CHECK_FORCE_SUGGESTS_: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Install JAGS on macOS
        if: runner.os == 'macOS'
        run: brew install jags

      - name: SET JAGS_HOME homebrew
        if: runner.os == 'macOS'
        run: |
          options(width = 100)
          Sys.setenv(JAGS_HOME="/usr/local/Cellar/jags/4.3.2")
        shell: Rscript {0}

      - name: Install JAGS on Windows (R release)
        if: (runner.os == 'windows') && (matrix.config.r != 'oldrel')
        run: |
          curl --progress-bar -s -o 'C:\JAGS-4.3.1.exe' -L 'https://sourceforge.net/projects/mcmc-jags/files/JAGS/4.x/Windows/JAGS-4.3.1.exe'
          C:\JAGS-4.3.1.exe /S

      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rcmdcheck
            any::XML
            any::covr
          needs: check


      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true

      - name: Test coverage
        run: |
          covr::codecov()
        shell: Rscript {0}
